definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      emailId:
        type: string
    required:
    - emailId
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.ReserveSeatRequest:
    properties:
      passengerAge:
        minimum: 1
        type: integer
      passengerName:
        type: string
      passengerPhone:
        type: string
      seatNumber:
        maximum: 300
        minimum: 1
        type: integer
    required:
    - passengerAge
    - passengerName
    - passengerPhone
    - seatNumber
    type: object
  dto.ReserveSeatResponse:
    properties:
      message:
        type: string
    type: object
  dto.ResetSeatsResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: User login request body
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Invalid request format
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User Login
      tags:
      - Auth
  /seat/reserve:
    post:
      consumes:
      - application/json
      description: Reserves a specific seat for a passenger
      parameters:
      - description: Seat reservation details
        in: body
        name: reserveSeatRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ReserveSeatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Seat reserved successfully
          schema:
            $ref: '#/definitions/dto.ReserveSeatResponse'
        "400":
          description: Invalid request format
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Reserve a seat
      tags:
      - Seats
  /seat/reset:
    post:
      description: Resets all reserved seats (Admin access only)
      produces:
      - application/json
      responses:
        "200":
          description: All seat reservations reset successfully
          schema:
            $ref: '#/definitions/dto.ResetSeatsResponse'
        "401":
          description: Unauthorized access
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Reset all seat reservations
      tags:
      - Seats
swagger: "2.0"
